# Build settings
markdown: redcarpet
highlighter: pygments

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Site settings
title: "观云博客"
description: > # this means to ignore newlines until "email:"
   用简单的方式说一说复杂的白酒。

email: mua@guanyun.cn
logo: "/assets/images/gy_logo.jpg"
cover: "https://cdn.thexstore.cn/blog.banner.jpg"

name: '观云'
authors:
  chn:
    name: '采花娘'
    avatar: "/assets/images/chn.jpg"
  czy:
    name: '陈振宇'
    avatar: "/assets/images/czy.jpg"

paginate:	5

url: "https://blog.guanyun.cn"
baseurl: ""

# social icons and sharing options
social:
  - icon:	weibo
    url:	http://weibo.com/GuanYunStore
    desc:	Follow me on 微博
    share_url: http://service.weibo.com/share/share.php
    share_title: ?title=
    share_link: "&amp;url="

  - icon:	twitter
    url:	https://twitter.com/GuanYunStore
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
